# Generated by Django 3.1.4 on 2020-12-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='user',
            new_name='name',
        ),
    ]
