# Generated by Django 3.1.4 on 2020-12-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201212_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='departments',
            field=models.CharField(choices=[('pwslabdevops', 'PWSLab DevOps Support'), ('isupport', 'iSupport')], default='pwslabdevops', max_length=20),
        ),
        migrations.AddField(
            model_name='status',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
