# Generated by Django 3.1.4 on 2020-12-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201212_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('open', 'Open'), ('close', 'Close'), ('error', 'Error')], max_length=20),
        ),
    ]
